### PR TITLE
:hammer: fix: writing correct app name inside the package.json and lock files

### LINKED ISSUE #7: Set directory name as a package name in package.json file
After `create-abell-app`, currently, the default name of the template is carried in the final app as well. Would be great if we could change the name in package.json with the directory name. `create-abell-app <directory-name>`

### PR DESCRIPTION
**Pull request by PranjalAgni**
Fixes #7 
Fixed the app name in package.json,  package-lock.json

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -127,11 +127,51 @@ const colors = {
...
+
+/**
+ * @param {String} appPath path of the app
+ * @description Creates a list of json files to be modified and invokes the updateFN parllely 
+ * @returns {Promise} 
+ */
+async function setCorrectAppName(appPath) {
+  try {
+    const currentDirectory = process.cwd();
+    const appName = appPath.split(path.sep).pop();
```
Comment (saurabhdaware) [inline lib/utils.js:155]: We can replace this with,
```suggestion
    const appName = path.basename(appPath)
```
This will be more readable and reliable I guess

File: lib/utils.js [hunk 2]
```diff
@@ -127,11 +127,51 @@ const colors = {
...
+    const packageFilesRegex = new RegExp(/^(package|package-lock).json$/);
+    const packageFilesList = fs
+    .readdirSync(appPath)
+    .filter(packageFilesRegex.test.bind(packageFilesRegex))
+    .map(file => path.join(currentDirectory, appPath, file));
+
+    const modifyPackagePromiseList = packageFilesList.map(pFile => updatePackageJson(pFile, appName));
+    await Promise.all(modifyPackagePromiseList);
```
Comment (saurabhdaware) [inline lib/utils.js:163]: We can ignore the name field in `package-lock.json` since it will be automatically updated after other npm operations and it doesn't really matter as package.json will be considered as a truth.

So we can have a single `updatePackageJson` call
```suggestion
    await updatePackageJson(path.join(process.cwd(), appPath, 'package.json'), appName)
```

**Review by saurabhdaware — CHANGES_REQUESTED** [review]
Hi @PranjalAgni, I've tested it locally and it works great! I've suggested some changes below. Let me know if they make sense. Thank you! :D

File: lib/utils.js (hunk 1 above)
Comment (PranjalAgni) [reply lib/utils.js:155]: Sure, this looks more cleaner and readable

File: lib/utils.js (hunk 2 above)
Comment (PranjalAgni) [reply lib/utils.js:163]: Yup if we are changing `package.json` then this can be done

Comment (PranjalAgni) [reply lib/utils.js:163]: Will make these changes and push

Comment (PranjalAgni) [reply lib/utils.js]: Made the appropriate changes, have a look

**Review by saurabhdaware — APPROVED** [review]
Awesome! Thank you so much @PranjalAgni :tada:

File: lib/utils.js [hunk 3]
```diff
@@ -127,11 +127,44 @@ const colors = {
...
+
+/**
+ * @param {String} appPath path of the app
+ * @description Creates a list of json files to be modified and invokes the updateFN parllely 
+ * @returns {Promise} 
+ */
+async function setCorrectAppName(appPath) {
+  try {
+    const appName = path.basename(appPath)
+    const packagePath = path.join(process.cwd(), appPath, 'package.json');
```
Comment (PranjalAgni) [inline lib/utils.js:155]: Written this on a separate  line, makes it more readable

Comment (saurabhdaware) [reply lib/utils.js:155]: yup makes sense. Thank you!

**Comment by PranjalAgni** [comment]
Just one thing I wanted to mention, that while testing my changes I found that after choosing yarn as installer to install my deps, it was using npm only.

**Comment by saurabhdaware** [comment]
ops I recently refactored and forgot to add the yarn code. Thank you so much! I will make those changes
